//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RailTransport
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Passenger
	{
		public virtual Ticket Ticket
		{
			get;
			set;
		}

		public virtual bool HasBaggage
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			private set;
		}

		public Passenger(string name)
		{
		}

	}
}

