//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RailTransport
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Ticket
	{
		public int NumberTrain
		{
			get;
			private set;
		}

		public Ticket(int numberTrain)
		{
            NumberTrain = numberTrain;
		}

	}
}

