//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RailTransport
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Train<T>
	{
		public virtual int Length
		{
			get;
			private set;
		}

		public virtual int Number
		{
			get;
			protected set;
		}

		public abstract void Sort();

		public abstract void RemoveAllCars();

		public abstract void AddCar(T car);

		public abstract void AddCars(T‎[] cars);

		public abstract void RemoveCar(T car);

	}
}

